#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | gitsecret:help)
    help_content_func () {
      declare desc="manage secrets in repo with git-secret"
      cat<<help_content
    gitsecret:reveal, Manage secrets in repo with git-secret
help_content
    }

    if [[ $1 = "gitsecret:help" ]] ; then
        echo -e 'Usage: dokku git-secret:reveal'
        echo ''
        echo 'Manage git-secret gpg key for server.'
        echo ''
        echo 'Example:'
        echo ''
        echo '$ dokku gitsecret:reveal'
        echo '<gpg public key content>'
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
