#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE_SOURCE_TYPE="$2"; TMP_WORK_DIR="$3"; REV="$4"

if ! which git-secret >/dev/null 2>&1; then
  dokku_log_fail "Missing git-secret!"
fi

echo ls -la $TMP_WORK_DIR
echo $REV
