#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; IMAGE_SOURCE_TYPE="$2"; TMP_WORK_DIR="$3"; REV="$4"

if ! which git-secret >/dev/null 2>&1; then
  dokku_log_warn "Missing git-secret, so cannot reveal any secrets for ${APP}!"
  exit 0
fi

if ! git -C $TMP_WORK_DIR rev-parse >/dev/null 2>&1; then
  dokku_log_warn "Directory is not a git repo, so cannot reveal any secrets for ${APP}!"
  exit 0
fi

if ! -d "$TMP_WORK_DIR/.gitsecret"; then
  dokku_log_info "gitsecret not enabled for ${APP}."
  exit 0
fi

cd $TMP_WORK_DIR
git secret reveal
