#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

cmd-gitsecret-reveal() {
  declare desc="reveals the servers gpg public key"
  declare cmd="gitsecret:reveal"
  [[ "$1" == "$cmd" ]] && shift 1

  gpg --armor --export $(hostname)
}

cmd-gitsecret-reveal "$@"
